train_dataset: mini-imagenet
train_dataset_args: {root_path: /path/to/the/root/folder/, split: train}
tval_dataset: mini-imagenet
tval_dataset_args: {root_path: /path/to/the/root/folder/, split: test}
val_dataset: mini-imagenet
val_dataset_args: {root_path: /path/to/the/root/folder/, split: val}

# Add num_sampling to the dataset parameters to enable IRD
# train_dataset: mini-imagenet
# train_dataset_args: {root_path: /path/to/the/root/folder/, split: train, num_sampling: 5}
# tval_dataset: mini-imagenet
# tval_dataset_args: {root_path: /path/to/the/root/folder/, split: test, num_sampling: 5}
# val_dataset: mini-imagenet
# val_dataset_args: {root_path: /path/to/the/root/folder/, split: val, num_sampling: 5}

load_encoder: /path/to/saved/pre-trained/model.pth




model: kgsa
model_args: 
    encoder: resnet12
    encoder_args: {avg_pool: True}
    temp: 15.0
    temp_learnable: False
    n_vecs: 5
    n_hidden: 50
    n_layer: 1
    dropout: 0.5
  

freeze_bn: False

batch_size: 100

n_way: 5
n_shot: 1
n_query: 15
train_batches: 200
ep_per_batch: 2

max_epoch: 100
optimizer: sgd
optimizer_args: {lr: 5.e-5, weight_decay: 5.e-4, milestones: [60], gamma: 0.1}

visualize_datasets: False

tensorboard_path: /path/to/the/root/folder/tensorboard/
save_path: /path/to/the/root/folder/
tolerance: 10
seed: 100
