train_dataset: mini-imagenet
train_dataset_args: {root_path: /path/to/the/root/folder/, split: train, augment: resize, mode: normal}
val_dataset: mini-imagenet
val_dataset_args: {root_path: /path/to/the/root/folder/, split: val, mode: normal}
fs_dataset: mini-imagenet
fs_dataset_args: {root_path: /path/to/the/root/folder/, split: test}
eval_fs_epoch: 5

model: classifier
model_args:
    encoder: resnet12
    encoder_args: {}
    classifier: linear-classifier
    classifier_args: {n_classes: 64}



batch_size: 128
max_epoch: 500
optimizer: sgd
optimizer_args: {lr: 0.1, weight_decay: 5.e-4, milestones: [350, 400, 440, 460, 480]} #ResNet-12


save_epoch: 50
visualize_datasets: False

save_path: /path/to/the/saved/folder/

